title: Blinky-Lite
description: Blinky-Lite
theme: "just-the-docs"
# remote_theme: pmarsceill/just-the-docs

url: ""
logo: "/assets/images/project-logo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: blinky
footer_content: "Copyright &copy; 2020-2023 BL Monitor & Control AB. Distributed by an <a href=\"https://raw.githubusercontent.com/Blinky-Lite/blinky-box-tutorial/master/LICENSE\">MIT license.</a>"


aux_links:
  Blinky-Lite on GitHub: https://github.com/Blinky-Lite
