version: "3.7"
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - NO_AUTOUPDATE=false
networks:
  default:
    name: tunnel
    external: true
